name    'redhat-puppet_dev'
version '0.0.10'
source 'UNKNOWN'
author 'redhat'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib'
